export { default as leftYellow } from "./leftyellow.svg";
export { default as leftSpiral } from "./leftSpriral.svg";
export { default as spiral3} from "./spiral3.svg";
export { default as code} from "./code.svg";
export { default as fragments} from "./fragment.png";
export { default as js} from "./js.svg";
export { default as python } from "./python.svg";
export { default as twingle } from "./twingle.svg";
export { default as fragmentSlide } from "./fragmentSlide.png";
export { default as fragmentDivide } from "./fragmentDivide.png"; 
export { default as sign } from "./sign.png"; 
export { default as upArrow } from "./upArrow.png"; 
export { default as topLayer } from "./topLayer.png";
export { default as bgOA } from "./bgOA.svg";
// export {default as AIC } from "./AIC.svg";
// export { default as boiko } from "./boiko.svg";
// export { default as founderX } from "./FounderX.svg";
// export { default as nammaFlutter } from "./Nammaflutter.svg";
// export {default as ofia } from "./ofia.svg";
// export { default as SFM} from "./SFM.svg";
export { default as partners } from "./partners.svg";
