export { default as AIC} from "./aic.svg";
export { default as BOIKO } from "./boiko.svg";
export { default as DUSKCODER } from "./duskcoder.svg";
export { default as FIA } from "./fia.svg";
export { default as FOUNDERX } from "./founderx.svg";
export { default as JPINFOTECH } from "./jpinfotech.svg";
export { default as NAMMAFLUTTER } from "./namma_flutter.svg";
export { default as SFM } from "./sfm.svg";
export { default as SNIPPET } from "./snippet.svg";
export { default as HIRENOW} from "./hirenow.svg";

export { default as Nammasocials } from "./Nammasocials.png";
export { default as Lecture_head } from "./lecture_head.png";
export { default as Namma } from "./namma.png";
export { default as Lecture } from "./lecture.png";
export { default as BobMaassy } from "./Bob Maassy.png";
export { default as PSP } from "./PSP.png";
export { default as Sequestera } from "./Sequestera.png";
export { default as SMVEC } from "./SMVEC.png";
export { default as Unstop } from "./Unstop.png";